### ISSUE TITLE
implement hugo for documentation

### ISSUE THREAD

**Issue by dch** [skunkwerks/swirl#8]
[hugo](http://hugo.spf13.com/overview/introduction) is a fast static site generator that doesn't require installing a continent of tools.
- [x] sort out yaml (see below for a start) & hugo incantation
- [x] add to the makefile
- [x] figure out how to lay out the docs
- [x] borrow a dark theme from [examples](https://github.com/spf13/hugo/tree/master/examples) or [themes](https://github.com/spf13/hugoThemes)
- [x] hook this up somehow with website generation - e.g. `make website` would rsync the merged website branch and output of hugo, or even merge the website into the hugo content, if that's possible
- [x] integrate syntax highlighting

`./doc/config.yaml`

``` yaml

---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
builddrafts: false
indexes:
    category: "categories"
baseurl: "http://swirl-project.org/doc"
title: "Bringing Live Streaming to the World"
permalinks:
    post: /:title/
```
